version: '3'

services:
  db:
    image: mysql
    restart: always
    container_name: movies-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=movies
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123